# Generated by Django 5.1.4 on 2025-10-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_owing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='owing',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='owing',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_type',
            field=models.CharField(default='Tuition', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('Tuition', 'Tuition'), ('Exam', 'Exam'), ('Development', 'Development'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20),
        ),
        migrations.AlterField(
            model_name='owing',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('EcoCash', 'EcoCash'), ('Bank Transfer', 'Bank Transfer'), ('Swipe', 'Swipe')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
